### ISSUE TITLE
[1.5pt] - Deploy Project - Group Task

### ISSUE THREAD

**Issue by HFG43** [HFG43/final_capstone_front_end#33]
- Create a `deployment` branch
- Use Heroku for deployment

**Comment by AndreaM2429** [comment]
Hello @HFG43!! @AndreaM2429 here!!

I implemented the deployment on render, you can find the live demo [here](https://gourmet-experiences-app.onrender.com).

Please check the live and give feedback if needed.

**Comment by HFG43** [comment]
Hi Andre! @AndreaM2429 Awesome job using render! The app looks fantastic! Very happy to see the project at this stage!

**Comment by AndreaM2429** [comment]
Thanks for taking the time to review this Hernán.
